version: "3.8"
services:
  ocsigen:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ocsigen
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    environment:
      - OPAMYES=true
      - OCAMLPARAM=_,bin-annot=1,strict-sequence=1
    tty: true
