version: "3"
services:
  ocaml:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/home/opam/app
    #command: "opam exec -- dune exec -- ./bin/main.exe"
    command: "tail -f /dev/null"
